### ISSUE TITLE
Why is defaultStartIndex 1 ?

### ISSUE THREAD

**Issue by kskumgk63** [elimity-com/scim#103]
Hi there!

I am wondering why `defaultStartIndex = 1`.
https://github.com/elimity-com/scim/blob/1bc6b4a9715467679091130ef48e1051ea1f9c21/server.go#L16

Using `defaultStartIndex` as an offset to use as-is, I could not get the first record from PostgreSQL.

Is it should be `0`??

I want to know your opinions.

**Comment by kskumgk63** [comment]
@di-wu Do you have any ideas?

**Comment by di-wu** [comment]
> **startIndex**:  The **1-based** index of the first result in the current set of list results. ...

You should convert it yourself in the implementation.
They probably chose a 1-based index for readability.

RFC: https://tools.ietf.org/html/rfc7644#section-3.4.2

**Comment by kskumgk63** [comment]
@di-wu Thanks for your answer!
