### ISSUE TITLE
Count can never be zero

### ISSUE THREAD

**Issue by mokiat** [elimity-com/scim#110]
Hi,

First off, thanks for the nice library.

According to the spec, when doing a GetAll a query argument of zero or negative would indicate that the resources need only be counted:
https://tools.ietf.org/html/rfc7644#section-3.4.2.4

> Specifies the desired maximum number of query results per page, e.g., 10.  A negative value SHALL be interpreted as "0".  A value of "0" indicates that no resource results are to be returned except for "totalResults".

The same is documented in your godoc:
https://pkg.go.dev/github.com/elimity-com/scim#ListRequestParams

However, in reality a check in the server prevents the `count` value from ever being anything less than 1, hence such a query is impossible to perform:
https://github.com/elimity-com/scim/blob/712f323175c85e30e8afad4c354a85882070d979/server.go#L163

**Comment by mokiat** [comment]
Thanks! Checked the fix today and it works.

**Comment by di-wu** [comment]
@mokiat, you're welcome! Thank you for reporting this.
