### ISSUE TITLE
Feature request: Option to disable validation

### ISSUE THREAD

**Issue by mokiat** [elimity-com/scim#112]
Hi,

Would it be possible to have an option on the Server (for example), that would allow one to disable the validation? In particular, I am most interested in disabling the validation for the Patch endpoint. The main reason for this is that it seams that there isn't really a consensus on how it should work and this mostly boils down to the specification not been thorough enough. Let me try to explain.

Let's take Azure's SCIM implementation as an example. Their previous client implementation would send the following PATCH operation to update a user's `givenName`:

```json
{
  "op": "replace",
  "path": "name.givenName",
  "value": "John"
}
```
and now their most recent implementation, uses the following model:

```json
{
  "op": "replace",
  "value": {
    "name.givenName": "John"
  }
}
```

Now, neither of these passes the validation logic of this project. And this project is probably correct. When you look at the specification, the only mention of a complex attribute is the following:

> If the target location specifies a complex attribute, a set of sub-attributes SHALL be specified in the "value" parameter, which replaces any existing values or adds where an attribute did not previously exist.
> https://tools.ietf.org/html/rfc7644#section-3.5.2.3

So the correct approach would likely have to be:

```json
{
  "op": "replace",
  "path": "name",
  "value": {
    "givenName": "John"
  }
}
```

And this one, I believe, passess the validation check.

However, the specification is just too vague on this. None of the examples they provide shows how singular complex attributes are modified and this leads to implementations having to guess or assume.

However, even this library probably makes a mistake. When it comes to boolean attributes (like `active`), it expects the `value` field to be of type boolean. However, if you read the specification it says that the `value` field will either be a quoted string (meaning `"true"`, not `true`) or a JSON object:
 
 > The value MAY be a quoted value, or it may be a JSON object containing the sub-attributes of the complex attribute specified in the operation's "path".
 > https://tools.ietf.org/html/rfc7644#section-3.5.2.1
 
However, this understanding, that active should instead be a boolean, seems to be common in the community, as seen in this thread:
https://stackoverflow.com/questions/59264809/azure-user-group-provisioning-with-scim-problem-with-boolean-values
In fact, after a recent change, Azure changed their implementation so that active is sent as a boolean and not as a string.

Furthermore, there may be situations where it would be ok to ignore a PATCH operation on a field that is not part of the schema, in the name of flexibility / interoperability.

I guess, end of the day, I would really like to be able to support Identity Providers, even if their implementation is slightly out of spec.

**Comment by jdeflander** [comment]
Thank you for the comprehensive issue! I understand why disabling validation could be useful in some cases. However, I'm not yet sure how it should work exactly:

- Should the library support disabling validation per PATCH endpoint?
- Should disabling validation only affect the `PatchRequest.Value` field?

I'm also wondering whether this should be a library feature, or if it can also reasonably be covered by manually placing a HTTP handler in front of the SCIM server.

**Comment by mokiat** [comment]
I considered the HTTP handler approach. What I don't particularly like about it is that you need to do the parsing all over again. I will try and do some experiments to see how it looks and whether it might actually be ok.

Side note: After digging a bit in the code and doing some debugging it seems that even the following does not work:
```
{
  "op": "replace",
  "path": "name",
  "value": {
    "givenName": "John"
  }
}
```

That is, I am not sure there is any valid way to replace a complex attribute at the moment, so there might be a bug here. Interestingly, the library accepts a path of the form `name.givenName` but then fails the validation afterwards for some reason. It could be that I am just doing something wrong. Will need to dig deeper.

**Comment by mokiat** [comment]
Ok, so there seems to be a bug in the library. I will open a separate issue.

**Comment by jdeflander** [comment]
> So this Feature Request issue remains valid and open for consideration.

I propose to reconsider this once #113 has been fixed, since after rereading the spec I'm no longer sure whether the examples from Azure are actually invalid.

**Comment by di-wu** [comment]
Hey @mokiat, here is a small update.

---

The following PATCH operations are now fixed:
https://github.com/elimity-com/scim/blob/e7b386cb713c3a8eece8d0836b0b6ecd2a6780de/testdata/patch/add/complex.json#L6-L23
All the operations above are now valid.

In the coming days I will also add two sets of tests that contain the examples given by both Okta and AzureAD. 

Let me know if you need something else.

**Comment by mokiat** [comment]
@di-wu thank you. I will try and test it out these days.

**Comment by mokiat** [comment]
It seems you have made quite the changes since I have last pulled. It will take more effort to integrate this back into the codebase. It will take more time to verify the new PATCH. Just a heads up.

**Comment by di-wu** [comment]
Sorry for all the breaking changes. 😅 
I hope to make a `v1.0.0` release one of the next weeks.

**Comment by di-wu** [comment]
@mokiat, I'll close this for now.
If there are still unresolved issues, feel free to open another issue!
