### ISSUE TITLE
`null` is returned by List calls returning no items when an empty array is required 

### ISSUE THREAD

**Issue by 200sc** [elimity-com/scim#127]
These lines:

``` go 
// return empty slice instead of null if there are no resources.
var resources []interface{}
for _, v := range page.Resources {
    resources = append(resources, v.response(resourceType))
}
```
https://github.com/elimity-com/scim/blob/master/handlers.go#L259-L263

Do the opposite of what the comment asks: `var resources []interface{}` is nil, and will stay nil unless `page.Resources` has items in it. 

This causes services like Azure to quarantine provisioning, expecting an empty array instead.  

The fix that worked for us was to replace the var declaration with a `:=` declaration, or a `make`.

**Comment by di-wu** [comment]
> Resources ...
> REQUIRED if "totalResults" is non-zero.

This is a valid response by the specification, since `Resources` is not required if `totalResults` is zero.

The following also counts for multi-valued attributes:
> Unassigned attributes, the null value, or an empty array SHALL be considered to be equivalent in "state".

---

I don't mind changing this to an empty slice.

**Q**: What if another IdP expects `null` instead of an empty array?

---
Sources:
[RFC7644](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2) | [RFC7643](https://datatracker.ietf.org/doc/html/rfc7643#section-2.5)

**Comment by 200sc** [comment]
I'll look into it on the Azure side some more, maybe there's a way to report spec problems to them. I agree that fixing it here isn't ideal, given that line from the spec. 

In the meantime we might add a json transformation layer wrapping this library to give azure what it wants.

**Comment by di-wu** [comment]
Another option:

We offer a choice to implementer.
Depending on the `Resources` we get from the `Page` struct, we can:

1. return `nil` if we receive a `nil` in the `Resource` attribute.
2. `[]`, if we get an empty slice.

**Comment by 200sc** [comment]
That would be the least surprising behavior, and sounds good to me.

**Comment by di-wu** [comment]
@200sc hope this solves your issue!

We are working towards a `v1` release. So let me know if there are any other issues!
