### ISSUE TITLE
It's not possible to place a placeholder in SCIM endpoints. can we somehow provision the same?

### ISSUE THREAD

**Issue by DaminiBansal** [elimity-com/scim#155]
For now, created http handle like this
http.Handle("/scim/", http.StripPrefix("/scim", &server))
which listens requests on /scim/v2/Users or Groups

can we handled this case somehow
/{randomString}//scim/v2/Users

Is there a provision to do the same using this library?

**Comment by suqin-haha** [comment]
https://github.com/elimity-com/scim/pull/156 
created a pull request to solve this problem, not sure when it will be merged tough. looks the author not active anymore
