### ISSUE TITLE
Filter functionality not available for use behind internal package

### ISSUE THREAD

**Issue by tyng94** [elimity-com/scim#160]
Context: We have an existing auth server using Gin and we have a requirement to implement SCIM on some of the endpoints, so we imported this package into our existing service and do an internal redirect from the gin server.

The problem we are facing is trying validate the resources before returning the results. Since the filter package in under `internal` we are unable to import and use it. We have fixed the problem by[ forking this repo](https://github.com/tyng94/scim), and simply moving the entire package out of `internal`.

Could we make this change to enable this filter functionality and other users who want to use this scim on top of other existing server frameworks out there?

**Comment by q-uint** [comment]
We're had this discussion before at: https://github.com/elimity-com/scim/issues/137#issuecomment-987620877.

I guess since a lot of people are requesting it, we might want to consider making it publicly accessible.
