### ISSUE TITLE
Sub Attributes in Schema

### ISSUE THREAD

**Issue by quantumew** [elimity-com/scim#67]
I noticed the schema for complex types is not quite marshaling right. The `subAttributes` field is being marshalled as `{}`. Looks like an easy fix. Going to try getting a PR soon.

Looks like it just needs to be handled here:
https://github.com/elimity-com/scim/blob/307c22b7fcf7291d390e867f456e5b87f08f2447/schema/schema.go#L116

**Comment by di-wu** [comment]
Thanks! Could you also add a test case that covers this? 
This way we can prevent this mistake again in the future.
