### ISSUE TITLE
ExternalId is missing on resources

### ISSUE THREAD

**Issue by xonstone** [elimity-com/scim#84]
It seems that externalId is not available on returned resources even tho it has been added as an attribute when you are using the Core schema (attributes not in the schema are filtered).

We are looking into adding this but seeing that this is a [common attribute](https://tools.ietf.org/html/rfc7643#section-3.1) we would add it in the same locations as ID (and treat it the same way). Like this: https://github.com/elimity-com/scim/blob/f934e79b8e439cf9849023d8fd45dc6bd4a01660/resource_handler.go#L52

Does this sound like the approach you want to take as well @di-wu ?

**Comment by di-wu** [comment]
Since it is indeed a [Common Attribute](https://tools.ietf.org/html/rfc7643#section-3.1) it should be located as a field in the `Resource` struct next to `ID`. Beware this attribute is optional.

**Comment by xonstone** [comment]
I've investigated this and it seems that the outgoing flow will not be a problem but the incoming will be.

Since the incoming mapping relies on having access to the Resource we would need to change
```
type ResourceHandler interface {
	// Create stores given attributes. Returns a resource with the attributes that are stored and a (new) unique identifier.
	Create(r *http.Request, attributes ResourceAttributes) (Resource, errors.PostError)
	// Get returns the resource corresponding with the given identifier.
	Get(r *http.Request, id string) (Resource, errors.GetError)
	// GetAll returns a paginated list of resources.
	GetAll(r *http.Request, params ListRequestParams) (Page, errors.GetError)
	// Replace replaces ALL existing attributes of the resource with given identifier. Given attributes that are empty
	// are to be deleted. Returns a resource with the attributes that are stored.
	Replace(r *http.Request, id string, attributes ResourceAttributes) (Resource, errors.PutError)
	// Delete removes the resource with corresponding ID.
	Delete(r *http.Request, id string) errors.DeleteError
	// Patch update one or more attributes of a SCIM resource using a sequence of
	// operations to "add", "remove", or "replace" values.
	Patch(r *http.Request, id string, request PatchRequest) (Resource, errors.PatchError)
}
```
to 
```
type ResourceHandler interface {
	// Create stores given attributes. Returns a resource with the attributes that are stored and a (new) unique identifier.
	Create(r *http.Request, resource Resource) (Resource, errors.PostError)
	// Get returns the resource corresponding with the given identifier.
	Get(r *http.Request, id string) (Resource, errors.GetError)
	// GetAll returns a paginated list of resources.
	GetAll(r *http.Request, params ListRequestParams) (Page, errors.GetError)
	// Replace replaces ALL existing attributes of the resource with given identifier. Given attributes that are empty
	// are to be deleted. Returns a resource with the attributes that are stored.
	Replace(r *http.Request, id string, resource Resource) (Resource, errors.PutError)
	// Delete removes the resource with corresponding ID.
	Delete(r *http.Request, id string) errors.DeleteError
	// Patch update one or more attributes of a SCIM resource using a sequence of
	// operations to "add", "remove", or "replace" values.
	Patch(r *http.Request, id string, request PatchRequest) (Resource, errors.PatchError)
}

```

Thoughts?

**Comment by di-wu** [comment]
So you want to change `ResourceAttributes` to `Resource` in the `Create()` and `Replace()` handlers?

I would rather add another parameter to the callback than change it to a `Resource`.
Since `ID` and `Meta` are not needed in `Create()`, and `Meta` not in `Replace()`.

Another solution that would not alter the `ResourceHandler` is to pass the *externalId* through the `ResourceAttributes`. Yet this would require a few more changes, such as adding the *externalId* to the `CoreUserSchema()` so it passes the validation to the callback. 
I would still extract it from the attributes and at it to the `Resource` struct.

**Comment by xonstone** [comment]
I'm leaning towards 
> Another solution that would not alter the ResourceHandler is to pass the externalId through the ResourceAttributes.

Since adding another param to the callback might insinuate that this is not optional.

I think I can add it here so to not mess up the core schema: https://github.com/elimity-com/scim/blob/f934e79b8e439cf9849023d8fd45dc6bd4a01660/resource_type.go#L81

**Comment by di-wu** [comment]
I would also prefer to not make breaking changes.

We have an `optional` package so there is no confusion when something would be optional.
