### ISSUE TITLE
Make use of some scim types in the library when it's possible

### ISSUE THREAD

**Issue by legosx** [elimity-com/scim#87]
All of the scim types from the specs
https://tools.ietf.org/html/rfc7644#section-3.12
are pre-defined in the library but not all of them are used.

I believe that it's possible to cover some of them on the side of the library as it has a validation logic.

- invalidFilter
Currently `errors.ScimErrorBadParams` is returned but it should be just `errors.ScimErrorInvalidFilter`.

- mutability
Mutability is not checked. It should return `mutability` error in case when user tries to change immutable attributes that are defined immutable via the schema.

- invalidPath
Path isn't validated but might be validated with using the schema.

**Comment by di-wu** [comment]
At this point we expect that the implementation covers all these checks. 
We could indeed validate this in advance. I would love to see this added to the library.

If someone wants tackle this issue, let me know. Otherwise I will take a go at it in about two weeks.

**Comment by di-wu** [comment]
I will look at this Monday.
