### ISSUE TITLE
PATCH remove op with path filter always returns ScimErrorInvalidValue

### ISSUE THREAD

**Issue by nhinds** [elimity-com/scim#91]
Attempting to PATCH with a path filter always returns `ScimErrorInvalidValue`.

e.g. using the example from the RFC: https://tools.ietf.org/html/rfc7644#section-3.5.2.2
```
$ curl -si -X PATCH <server>/Groups/acbf3ae7-8463-...-9b4da3f908ce -d '{
  "schemas":
   ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
  "Operations":[{
    "op":"remove",
    "path":"members[value eq \"2819c223-7f76-...413861904646\"]"
  }]
}'
HTTP/1.1 400 Bad Request
Content-Type: application/scim+json
Date: Thu, 17 Sep 2020 05:46:58 GMT
Content-Length: 241

{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidValue","detail":"A required value was missing, or the value specified was not compatible with the operation or attribute type, or resource schema.","status":"400"}
```

This doesn't error when the "path" in the operation is simple, like `"path":"members"`, or when a "value" is provided - but I believe "remove" operations shouldn't specify a "value" param.

It seems like the operation validation [treats the path as if it is the name of an attribute](https://github.com/elimity-com/scim/blob/master/resource_type.go#L221), which causes the attribute validation to [always return ScimErrorInvalidValue](https://github.com/elimity-com/scim/blob/285be4a1157f81c4881ce20468a7ef01921cd259/schema/schema.go#L107) since there is no field `members[value eq "2819c223-7f76-...413861904646"]` in my schema.

The patch support added in #65 appeared to skip value validation if there was a path filter, but the latest code no longer skips the value validation like this.

**Comment by nhinds** [comment]
Ah, sorry - it looks like the support in #65 didn't handle this kind of "path" either, it just errors with slightly different output:
```
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"scimType":"invalidSyntax","detail":"The request body message structure was invalid or did not conform to the request schema.","status":"400"}
```

Seems like the original `op.HasPathFilter()` didn't consider `members[value eq "2819c223-7f76-...413861904646"]` to be a path filter.

Am I doing something wrong with this operation?

**Comment by di-wu** [comment]
Thank you for reporting this! You are not doing anything wrong, this is a bug in the code and has never worked properly.

The problem seems (as you indicated) that the `operationValue` in `ValidatePatchOperation` is the full path and will not match. I will look into it more later today and report back to you.
