### ISSUE TITLE
[Question] Why don't you support `/Bulk` ?

### ISSUE THREAD

**Issue by kskumgk63** [elimity-com/scim#95]
Hi,
I am using this wonderful library to implement the SCIM server.

If `/Bulk` was not supported, I fear that the number of requests from SCIM clients would be quite high and the server might not be able to handle it.

Therefore, I want to know why you don't support `/Bulk`.

I look forward to your reply.

**Comment by di-wu** [comment]
Hi  @kskumgk63! Thank you for using the library and provide feedback!

I have no reason to not support it, just have not come around to it. 

The goal of this project was to provide an easy interface for creating SCIM servers. It started with a bare **minimum** implementation of the protocol. This means _only required functionality_ was implemented. 

**Optional** features such as `filtering` and `patch` was later added on request by others who wanted to use the library. They also took it on themselves the add these by opening issues/PRs.

---

_TL;DR_
I've not come around to add all the optional functionalities. I would **love** to support the whole specification.
If you would like to tackle one of these, please to ahead! I look forward review these and provide feedback.

If you have more questions, let me know!

**Comment by kskumgk63** [comment]
Thank you for your replying @di-wu !

I would like to address this feature!!
Before I implement it, I want to ask you something.

Do you know any services to verify the feature?
I suppose I can verify the operation by unit testing, but I don't think that's enough.
I want to know what SCIM client service  you use.

**Comment by di-wu** [comment]
Great! Be sure to open issues so I know what you'll be working on.

I have used **Okta** and **AzureAD** in the past. Be careful using these. Some IdPs still contain inconsistencies with the protocol, so make sure to also take a look at the spec itself!

---

_Another note_: I am planning to remove `stretchr/testify` in the future, so don't use it in your unit tests!

**Comment by kskumgk63** [comment]
I understood your situation, so close this issue.

Thank you for your answer!!
